//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18051
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.0.30319.17929.
// 
namespace Aliencube.FeedSchemata.Extensions {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://purl.org/rss/1.0/modules/slash/")]
    [System.Xml.Serialization.XmlRootAttribute("slash", Namespace="http://purl.org/rss/1.0/modules/slash/", IsNullable=false)]
    public partial class Slash {
        
        private string[] itemsField;
        
        private ItemsChoiceType[] itemsElementNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("comments", typeof(string), DataType="positiveInteger")]
        [System.Xml.Serialization.XmlElementAttribute("department", typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("hit_parade", typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("section", typeof(string))]
        [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemsElementName")]
        public string[] Items {
            get {
                return this.itemsField;
            }
            set {
                this.itemsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ItemsElementName")]
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public ItemsChoiceType[] ItemsElementName {
            get {
                return this.itemsElementNameField;
            }
            set {
                this.itemsElementNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://purl.org/rss/1.0/modules/slash/", IncludeInSchema=false)]
    public enum ItemsChoiceType {
        
        /// <remarks/>
        comments,
        
        /// <remarks/>
        department,
        
        /// <remarks/>
        hit_parade,
        
        /// <remarks/>
        section,
    }
}
