//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18051
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.0.30319.17929.
// 
namespace Aliencube.FeedSchemata.DublinCore {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://purl.org/dc/elements/1.1/")]
    [System.Xml.Serialization.XmlRootAttribute("dc", Namespace="http://purl.org/dc/elements/1.1/", IsNullable=false)]
    public partial class DublinCore {
        
        private object[] itemsField;
        
        private ItemsChoiceType[] itemsElementNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("contributor", typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("coverage", typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("creator", typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("date", typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("description", typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("format", typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("identifier", typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("language", typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("publisher", typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("relation", typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("rights", typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("source", typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("subject", typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("title", typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("type", typeof(DcmiType))]
        [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemsElementName")]
        public object[] Items {
            get {
                return this.itemsField;
            }
            set {
                this.itemsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ItemsElementName")]
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public ItemsChoiceType[] ItemsElementName {
            get {
                return this.itemsElementNameField;
            }
            set {
                this.itemsElementNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://purl.org/dc/elements/1.1/")]
    public enum DcmiType {
        
        /// <remarks/>
        Collection,
        
        /// <remarks/>
        Dataset,
        
        /// <remarks/>
        Event,
        
        /// <remarks/>
        Image,
        
        /// <remarks/>
        InteractiveResource,
        
        /// <remarks/>
        MovingImage,
        
        /// <remarks/>
        PhysicalObject,
        
        /// <remarks/>
        Service,
        
        /// <remarks/>
        Software,
        
        /// <remarks/>
        Sound,
        
        /// <remarks/>
        StillImage,
        
        /// <remarks/>
        Text,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://purl.org/dc/elements/1.1/", IncludeInSchema=false)]
    public enum ItemsChoiceType {
        
        /// <remarks/>
        contributor,
        
        /// <remarks/>
        coverage,
        
        /// <remarks/>
        creator,
        
        /// <remarks/>
        date,
        
        /// <remarks/>
        description,
        
        /// <remarks/>
        format,
        
        /// <remarks/>
        identifier,
        
        /// <remarks/>
        language,
        
        /// <remarks/>
        publisher,
        
        /// <remarks/>
        relation,
        
        /// <remarks/>
        rights,
        
        /// <remarks/>
        source,
        
        /// <remarks/>
        subject,
        
        /// <remarks/>
        title,
        
        /// <remarks/>
        type,
    }
}
