//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.0.30319.18020.
// 
namespace Aliencube.FeedSchemata.Syndication {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://purl.org/rss/1.0/modules/syndication/")]
    [System.Xml.Serialization.XmlRootAttribute("sy", Namespace="http://purl.org/rss/1.0/modules/syndication/", IsNullable=false)]
    public partial class Syndication {
        
        private object[] itemsField;
        
        private ItemsChoiceType[] itemsElementNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("updateBase", typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("updateFrequency", typeof(string), DataType="positiveInteger")]
        [System.Xml.Serialization.XmlElementAttribute("updatePeriod", typeof(UpdatePeriod))]
        [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemsElementName")]
        public object[] Items {
            get {
                return this.itemsField;
            }
            set {
                this.itemsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ItemsElementName")]
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public ItemsChoiceType[] ItemsElementName {
            get {
                return this.itemsElementNameField;
            }
            set {
                this.itemsElementNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://purl.org/rss/1.0/modules/syndication/")]
    public enum UpdatePeriod {
        
        /// <remarks/>
        hourly,
        
        /// <remarks/>
        daily,
        
        /// <remarks/>
        weekly,
        
        /// <remarks/>
        monthly,
        
        /// <remarks/>
        yearly,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://purl.org/rss/1.0/modules/syndication/", IncludeInSchema=false)]
    public enum ItemsChoiceType {
        
        /// <remarks/>
        updateBase,
        
        /// <remarks/>
        updateFrequency,
        
        /// <remarks/>
        updatePeriod,
    }
}
